05-html-css/04-css-intro.md
Some of the formatting wasn't rendering properly, particularly around
the section on selectors. This is now fixed.
Re-labeled code segments from HTML to CSS so they will be correctly
syntax-highlighted.
Re-worded a couple things to increase clarity.
Re-formatted version can be found at https://github.com/droberts-ada/textbook-curriculum/blob/topics/CSS_selector_formatting/05-html-css/04-css-intro.md
=> Reformat Intro to CSS

09-intermediate-rails/08-vcr-testing.md
A student pointed out in class that using VCR would cause our slack
tokens to be committed to git. Since committing secrets to git is a Bad
Thing, I added a section about how to avoid doing that.
=> Add section on filtering sensitive data from VCR cassettes

11-Backbonejs/01-Introduction-to-Backbonejs.md
Since we're providing the students with a scaffold for all of their Backbone projects, which includes the Backbone library itself via npm, we should not give them conflicting instructions on downloading it.
=> Remove section on installing Backbone

11-Backbonejs/04-Backbone-Models.md, 11-Backbonejs/05-Backbone-Collections.md, 11-Backbonejs/xx-Backbone-Advanced-Collections.md
I've moved Chris's details on Collection functions to another file. This stuff is valuable and should definitely be addressed, but I don't think we'll have time tomorrow. It also doesn't fit well with the live code, and would feel tacked-on if we left it there - it really deserves its own space. Perhaps for Wednesday?
I found a bug in the Models lecture, where we forgot to re-delegate events when the `TaskView`s were redrawn. I've added a section addressing this.
As with the Models lecture, this one is split in two. The first part is about retrofitting the app to use a collection, without adding any new functionality. In the second part, we add the ability to remove a task from the list.
Once they've gotten through this, they should be pretty much ready for Rolodex!
=> Backbone Collections Lecture

11-Backbonejs/05-Backbone-Collections.md
In the Backbone Collections lecture, in the first part (retrofitting our
app to use collections), the code sample for createTask() was wrong. It
said we were changing render(), and used tabs instead of spaces. Not
quite sure how this happened, but it's fixed now.
=> Collections: fix first code sample for createTask

12-Capstone/deploy-aws-eb.md
Improve the live demo instructions for the AWS deployment w/ Elastic Beanstalk lecture. The instructions now include how to setup SSH access, and configure a necessary environment variable appropriately.
=> Update AWS EB live demo instructions

01-ruby-fundamentals/08-variables-and-scope.md
Turns out `if` statements in Ruby aren't actually blocks, and don't affect variable scope.
Also add a sentence on how parameters act like local variables.
N/A
Example code is much longer, and less whimsical. Will the method to find the best distract from the learning objective (variable scope)?
Adding Kari and Chris for feedback because one of you will be giving this lecture tomorrow.
=> Remove `if` from block example

04-cs-fundamentals/classroom/03-Sorting-Efficiency.md
O(2^N) is not O(N), so I'm guessing it should actually say O(2N) or O(2*N)
=> Fixed typo in "Nuances"

00-programming-fundamentals/xx-debug.md, 01-ruby-fundamentals/03-iteration-and-blocks.md, 01-ruby-fundamentals/03a-loop-table-worksheet.md, 03-leadership-and-inclusion/06b-Advocacy-Discussion.md, 03-leadership-and-inclusion/Creating Inclusive Community (Sarah).md, 03-leadership-and-inclusion/Implicit Bias (Sarah).md, 04-cs-fundamentals/internship/Arrays-LinkedLists.md, 04-cs-fundamentals/internship/Binary Search Trees.md, 04-cs-fundamentals/internship/Stacks and Queues.md, 05-html-css/00-alt-text.md, 05-html-css/00-css-intro.md, 05-html-css/00-floats-sundry.md, 05-html-css/00-html-divide-conquer.md, 05-html-css/00-semantics-best-practices.md, 05-html-css/00a-css-divide-conquer.md, 05-html-css/00b-css-practice.md, README.md
Recently GitHub decided to [create a formal spec](https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown) for GitHub Flavored Markdown.
One side effect of this, and the resulting updates to their Markdown parser & renderer, is that specifying a header without a space or new line following the hash characters will [create a paragraph instead](https://github.github.com/gfm/#example-34).
Apparently this was always invalid, but GitHub's earlier implementation allowed it so they decided to break backwards compatibility. As a result, I've updated our textbook repository in all instances where we used the invalid syntax.
I found the updated lines with automated searching, and changed them with automated substitution regular expressions.
If you find that you've an abundance of …
=> Fix Markdown headers

09-intermediate-rails/testing-auth.md
Removed all that junk about keeping track of a session in the test! Turns out you don't need it.
Substantially modified the way we interact with the mock data. We now set it explicitly before every login request, and the `login` helper function now takes a `User` object to log in as. That should enable some nice testing around multi-user interaction, should students find the time. Also, turns out the request was completely ignoring the `env` argument, so I've removed it for simplicity.
Added `What Did We Accomplish` section at the bottom, because this is a big sucker and I'll probably have forgotten what all we did by the time I'm done teaching it.
All the code snippets I used, particularly those interacting with the model, reflect the books oauth strategy and migrations and such we did …
=> Updates to OAuth Testing Resource

11-Backbonejs/Backbone-Views.md
I wanted to clarify our description of the `stopListening()` function from Backbone that was added when talking about `remove()` on Backbone Views.
=> Clarify definition of Backbone's `stopListening()`

01-ruby-fundamentals/literals.md
Removed bignum example - should never use it since ruby's integer class handles it. Unnecessary tangent to have it in this lesson.
- [ x] Section X still needs some more detailed examples
- [ x] Still need to add "Additional Resources"
none
=> Remove bignum example

01-ruby-fundamentals/intro-to-ruby-gems.md
Default use of the money gem will look for internationalization/locale config, and produce the following error:
```
`enforce_available_locales!': :en is not a valid locale (I18n::InvalidLocale)
```
For this example, turn off internationalization
=> turn off i18n features for the money gem example

10-JavaScript/jquery-events.md
We're moving our Codepen examples to a central Ada account found here: https://codepen.io/adadev/
I've also made some minor updates to the lecture to match these examples.
=> update code pen links to central Ada codepen account

11-Backbonejs/Introduction-to-Backbonejs.md, 11-Backbonejs/live-code-overview.md
Some minor wordsmithing on the teaser line that mentions Backbone Views.
This also moves the webpack video resource out of the intro file, because we no longer mention webpack in there, and into the live code overview (where that content was moved to).
=> Minor changes to Backbone Intro

11-Backbonejs/models.md
I reworded the instructions for how to do `import` statements with our project baseline, because we do not need to do relative paths when importing from within the `src/` directory.
Also changed `let` to `const` in code snippets and made some minor grammar changes.
=> Backbone Models curriculum cleanup

00-programming-fundamentals/code-coverage-and-simplecov.md
We haven't assigned Robot Name yet and the SimpleCov lecture references it.  I've changed it to reference the TDD exercise.  
- [ x ] Have you updated the weekly learning goals in the pedagogy resource
- Nope
=> Update Simplecov to not reference Robot Name WW

05-html-css/exercises/form_exercise.md, 05-html-css/html-forms.md, 05-html-css/solutions/form_exercise/contact.html
As it turns out, `input` elements are empty, so we can't put descriptive text within them (even if the browser will make it work). Instead we need to use labels for that in all cases.
Additionally, labels connect to input elements by matching the `for` and `id` tags, not `for`/`name`.
=> HTML forms: Minor changes to input and label elements

08-rails/reference/.rails-template.rb, 09-intermediate-rails/reference/.rails-template.rb
This adds necessary setup files for Guard to our Rails templates (both the initial and advanced versions).
I've tested this out with a new Rails project, and it seems to work fine. Feel free to test it out with any of our existing project scaffolds!
=> Add Guard to Rails templates

08-rails/rails-forms.md, 09-intermediate-rails/view-helpers.md
This started off with some review comments and turned into a much more substantial modification.
The overall impact of the changes is to introduce Rails forms more slowly, and to simplify earlier examples a bit.
I also made a choice to briefly mention the hidden input tags generated by Rails, and then leave them out of further code samples in order to minimize distractions.
I would highly suggest splitting this into two resources now, by splitting out all of the ActiveRecord related content.
=> Suggested changes to Rails forms lecture

React/props.md
We accidentally left a line in from the original class component code
snippet.
=> React props: Fix code snippet functional style

01-ruby-fundamentals/README.md
Fix link to friendship note exercise
The link to friendship note exercise is returning a 404 error. This is a fix for it.
=> Fix link to Friendship note exercise

00-programming-fundamentals/installfest.md
A suggestion to make the installfest default editor for git as nano.  At least you can read how to exit the editor on the screen.
If you don't think we should do this, just reject the PR.
=> Change default git editor to nano

08-rails/common-view-helpers.md
The goal was to reduce redundancy with the lessons on [route parameters](https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/08-rails/route-parameters.md) and [restful routing](https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/08-rails/restful-routing.md), which cover the same material in deeper detail earlier in the week.
- [N/A] Have you updated the weekly assessment in Schoology?
- [N/A] Have you updated the READMEs with links to new or moved resources?
None
Nothing special
=> Make view helper info on named paths consistent with other resources

10-JavaScript/exercises/setup-linting.md
Small addition to the linter set up to allow ES6 data structures like `Set`.
=> Update linters to allow ES6 additions like `Set`.

08-rails/installfest-rails.md
The tags --no-rdoc and --no-ri have been merged into new tag --no-document. See https://gitlab.com/gitlab-org/gitlab-ce/issues/55740
**N/A**
Are any of these items still in progress? **No**
=> Update to no-document gem tag

03-leadership-and-inclusion/Advocacy-Discussion.md
The current link hits a [404](http://ucop.edu/academic-personnel-programs//_files/seminars/Tool_Interrupt_Microaggressions.pdf) -- this PR [updates the link](https://academicaffairs.ucsc.edu/events/documents/Microaggressions_InterruptHO_2014_11_182v5.pdf).
=> Fix link to tool: interrupting microaggressions

00-programming-fundamentals/code-coverage-and-simplecov.md
We want to make sure students ignore `test/` when they are checking coverage.
=> Add exclude examples to all of the `SimpleCov.start`s

01-ruby-fundamentals/exercises/friendship-note.md, 01-ruby-fundamentals/exercises/object-vocabulary.md, 01-ruby-fundamentals/exercises/source/friendship-note.rb, 01-ruby-fundamentals/exercises/source/object-vocabulary/loan.rb, 01-ruby-fundamentals/exercises/source/object-vocabulary/patron.rb, 02-intermediate-ruby/class-methods-and-self.md, 02-intermediate-ruby/source/song.rb, 02-intermediate-ruby/testing-with-minitest.md
Exactly what it says on the tin. I did double check that all links go to the right place.
There are a number of gist links still in the Backbone section, but that's deprecated anyway so I figured it's not worth the trouble.
None
Nothing special
=> Remove gist links to my personal GitHub account

04-cs-fundamentals/internship/exercises/binary-tree.md
The code sample provided in the Binary Tree exercises had a bug in which the variable names used in the `initialize` method of the `TreeNode` class did not match the parameter names in the method signature.
=> Fixed code sample for TreeNode class in Binary Tree exercises

09-intermediate-rails/testing-oauth.md
Going over this lesson, there were a lot of clashes with [this previous activity](https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/09-intermediate-rails/oauth.md)
These changes make them consistent. I haven't looked into future lessons to see if they conflict with this at all.
=> change user properties to be named consistently with implementing oauth activity

09-intermediate-rails/api-creating-items.md
I just discovered that we'd had a line in our Post request lesson that no longer applies to current versions of Rails 5 or 6.  So I'm taking it out and making a note that you'd have to do something different if you had an App which served both HTML and JSON.
=> Remove the CSRF file update

10-JavaScript/variables-conditionals-iteration.md
to test equality we use === (not just for strings)
=> dropped "between strings"

React/testing.md
This is a rework to move testing from Enzyme towards the [React Testing Library](https://testing-library.com/docs/react-testing-library/intro), which is gaining steam lately.  It also introduces simulating dom events and verifying that callback functions are called and de-emphasizes snapshot testing, which I think is not fantastically useful.
=> React testing to React Testing Library

02-intermediate-ruby/testing-with-minitest.md
I changed the first test input from 8 hours to 11 hours, since we are initially not dealing with the issue of needing to prepend 0s. It seems make sense to have a simpler example and then note how this would change for single digit values.
=> first example: changed 8 hours to 11 hours

01-ruby-fundamentals/raising-exceptions.md
Removed duplicate "the" in the second sentence of the summary portion.
=> fix typo in summary

02-intermediate-ruby/api-post.md
Token instructions were out of date.
=> Update Slack token instructions for POST exercise

02-intermediate-ruby/testing-with-guard.md
I was trying to install guard today and ran into an issue:
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h
I found this post - https://github.com/castwide/vscode-solargraph/issues/78 - which suggested the problem is because my mac is 10.14 
I had to run this command which then allowed me to install guard.
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
I wanted to mention this to your team incase you want to include it, though you may not feel it is relevant to Ada students!
David
Please utilize the built-in GitHub Reviewers functionality to assign necessary …
=> Issue I encountered with install

08-rails/live-code-intro.md
If we don't run `rails db:migrate` we get this error. Do you think this is the point where students should do this?
/Users/becca/Documents/GitHub/AdaGold/ada-books/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/becca/Documents/GitHub/AdaGold/ada-books/config/application.rb to limit the frameworks that will be loaded.
=> rails db:migrate

08-rails/ERB-and-Layouts.md
the textbook curriculum said that `index.html.erb` was there, but since we manually created the `index` action, we also needed to manually create this view file.
=> index.html.erb file creation

08-rails/test-the-test-database.md
our sample fixtures files had columns that aren't relevant to our current curriculum
minitest will give warnings about outdated test syntax, so that's in here too
https://github.com/AdaGold/ada-books/tree/29-test-database
=> conforms yml files to current columns, updates to expect() test syntax

React/testing-user-interaction.md, React/testing.md
I'm removing references to the `cleanup` function because it's called automatically by Jest and the testing library now.  
I found out by reading the testing library's author blog.
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library?ck_subscriber_id=363847276
=> remove cleanup references because it's unnecessary now
