Ada-Developers-Academy/textbook-curriculum

- 05-html-css/01-the-web.md
@PilgrimMemoirs Just a suggestion on wording static sites.
> Suggested change to about static sites

- 05-html-css/02-html-intro.md
removed a few repeated words
also, in the Meowspace example changed references to a title, to a heading since it may be confusing since its using a heading tag and not the title tag
> Editing: removed repeated words, etc

- 00-programming-fundamentals/11-managing-git-branches.md
- 08-rails/16-partial-views.md
Updates to existing branching resource
Created a new resource specifically for partials
> Partial & Branching

- 04-cs-fundamentals/internship/Trees.md
@sudocrystal Need your help with merging this pull request too. Thank you!
> Update and rename Session2.md to Trees.md

- 04-cs-fundamentals/internship/Arrays-LinkedLists-Pointers.md
Added link to classroom handout on introduction to pointers. Updated page name.
@sudocrystal Need your help to merge the pull request. Feedback is welcome! Thank you.
> Update and rename Session1.md to Arrays-LinkedLists-Pointers.md

- 04-cs-fundamentals/internship/Binary Search Trees.md
Updating notes on Trees for the next session.
> Update and rename Trees.md to Binary Search Trees.md

- 08-rails/16-unit-testing-models-specs.md
The previous version worked, but this is simpler in test_helper.rb.
> revised test_helper.rb

- 05-html-css/15-css-framework.md
> A few updates for readability and clarity on css framework

- 05-html-css/15-css-framework.md
added note about foundation rails gem
> note about rails foundation gem, to not use

- 09-intermediate-rails/02-controller-filters.md
> One more pass on clarifications for controller filter

- 04-cs-fundamentals/internship/Stacks and Queues.md
Adding notes on Stacks and Queues
> Create Stacks and Queues.md

- 09-intermediate-rails/02-controller-filters.md
> Just Fixed missing comma.

- 09-intermediate-rails/05-view-helpers.md
@kariabancroft @droberts-ada 
Just added html_safe, because the given example wouldn't work otherwise.
> Added html_safe, need to test things first.

- 04-cs-fundamentals/internship/Stacks and Queues.md
@sudocrystal Need your help to merge these changes. Updates made in accordance with clarifying questions asked by students in class.
> Update Stacks and Queues.md

- 09-intermediate-rails/05-view-helpers.md
Including a nice table!
I know we just talked about having stuff ready *before* the night before, but I got a little excited while I was doing prep.
Edits to code are just indentation so that the Atom markdown preview would do the right thing.
> Add information about *when* to use View Helpers

- 09-intermediate-rails/01-session-and-oauth.md
> Added link to Heroku Env variables in oAuth notes.

- 04-cs-fundamentals/interview-prep/interview-questions-algorithms.md
Most of these commits are just organizational changes, but the following are my attempt to make the questions more clear and provide a more specific progression of difficulty for the students:
* 719e071 - WB questions: Reorder for increasing difficulty
* 49148cc - WP questions: Improve clarity on lists questions
Those should probably receive some scrutiny because my assumptions about what questions are more difficult, and especially my interpretation of what the questions are asking, could be wrong.
> Small changes to interview prep whiteboarding questions

- 09-intermediate-rails/xx-consuming-apis-in-rails.md
We'll need to adjust code samples, etc. to match whatever live code starter package we provide.
> Add textbook section on consuming an api in rails

- 09-intermediate-rails/10-creating-apis.md
- Notes that shall go along with a live code (linked in the notes) for the preparation for shipping service
- I updated the live code per some changes, the old on still is in AdaGold/ada-pets-old if you want to check it out
- TODO; update the live code with show tests
> API Creation

- 09-intermediate-rails/08-vcr-testing.md
They now include the possibility of failure! Previously we just called
listchannel. Now we call sendmsg with both a positive and a negative
case.
In order to get this working with POST params, I had to make VCR
sensitive to the body of requests, in addition to the method and URI.
Also fixed a couple of grammar and formatting things.
> Rework example tests

- 09-intermediate-rails/10-creating-apis.md
- Move all information about API optimizations down to an appendix.
- Add section on `as_json` filters, since that's included in the lecture's TDD (Kari actually mentioned this in her notes, but we never got around to it).
> Last minute changes to the Producing APIs textbook page

- 08-rails/18-testing-controllers.md
Inspiration struck while grading bEtsy.
> Add section about what sort of thing you should cover in controller tests

- 10-JavaScript/08-jquery-events.md
This also exists in 07-jquery-intro.md
> Remove duplicate section

- 10-JavaScript/02-fun-with-functions.md
Link to slides, plus MDN page on functions
> Add Additional Resources

- 10-JavaScript/01a-ruby-to-js-worksheet.md
Check out those non-breaking spaces!
> Fix numbering on Ruby to JS Worksheet

- 10-JavaScript/03-objects-and-inheritance.md
I think I did this in-line with what Kari was describing during lecture; please correct me if I missed something.
> updating capitalization

- 10-JavaScript/04-js-in-the-browser.md
- 10-JavaScript/05-jquery-intro.md
- Add section on running JS in the developer console
- Improve wording around the DOM
- Improve capitalization
> Improve the JS in the browser lecture

- 10-JavaScript/04-js-in-the-browser.md
* Expand on the details of how the DOM differs from HTML
* Expand on the details of how the DOM is structured, and how it relates to the contents of an HTML document
> Updates to JavaScript in the Browser curriculum

- 10-JavaScript/07-jquery-events.md
- Add motivation
- Expand discussion of callbacks and anonymous functions
- Add connection to `$(document).ready()`
- Talk about the `event` parameter
- Add in-class exercise via CodePen
> Substantially expand the jQuery Events lecture

- 10-JavaScript/09-ajax-intro.md
> Ajax lessons

- 10-JavaScript/09-ajax-intro.md
> ajax lesson final touches - still needs polishing

- 10-JavaScript/09-ajax-intro.md
- 10-JavaScript/10-ajax-post.md
> Add AJAX POST resource

- 11-Backbonejs/00-frameworks-vs-libs.md
- 11-Backbonejs/01-Introduction-to-Backbonejs.md
- 11-Backbonejs/02-Backbone-Views.md
- 11-Backbonejs/03-Backbone-Models.md
- 11-Backbonejs/04-Backbone-Collections.md
- Just minor updates and clarifications to backbone notes
- Added a preliminary discussion resource for frameworks vs libraries (which could use some additions, maybe a video?)
> Backbone Updates

- 11-Backbonejs/00-frameworks-vs-libs.md
> Expand the framework vs lib discussion

- 11-Backbonejs/02-Backbone-Views.md
There's a lot of content here. It may be this is the entire morning, and we don't get to events until after lunch. I think I would be OK with this so long as there are plenty of breaks.
It's also lacking in the "OK, now you go figure it out" department. I'm not quite sure how to fit this in - maybe @PilgrimMemoirs has some ideas?
> Bring the View lecture in line with the expected live code

- 11-Backbonejs/06-Adding-Custom-Events.md
Took out content related to the removed event bus technique, not being very useful for us at this point.
> Revised learning goals.

- 10-JavaScript/11-testing.md
Still need to:
- Add the links to the starter code
> Add jasmine testing resource

- 10-JavaScript/11-testing.md
We have had several students missing the fact that they need to change the imports from the node app to work in our webpack framework.
> Small fix testing

- 11-Backbonejs/07-JavaScript-Objects-to-Backbone-Models.md
Spelling, grammar, closing braces
> Small formatting fixes

- 11-Backbonejs/07-Backbone-Review.md
Added a new directory for capstone lessons 
n/a
None.
> Capstone Directory

- 12-Capstone/deploy-aws-eb.md
This is the initial version of the Deploying to AWS with Elastic Beanstalk lecture notes.
Feedback would be great, but I haven't left enough time for it to be integrated before the lecture starts.
> Initial version of Deploying to AWS with Elastic Beanstalk

- 12-Capstone/deploy-aws-eb.md
Minor fix to markdown formatting.
> Fix spacing on learning goals in AWS deployment

- 12-Capstone/ssl.md
Unfortunately, heroku only allows this if you pay, so I've mostly just
provided a link.
N/A
N/A
> Cover deploying letsencrypt certs to Heroku

- 12-Capstone/ssl.md
Minor formatting change
N/A
N/A
> Fix formatting on code snippets inside lists

- 00-programming-fundamentals/06-submitting-projects-v1.md
This adds a simple definition for the term repository (as we use it elsewhere within the document) with a couple of examples. It also adds an example to the definition of fork.
Are these reasonable examples to use? Should we add an example of a pull request?
> Expand vocabulary section in Project Submission doc

- 00-programming-fundamentals/01-how-to-osx.md
- 00-programming-fundamentals/02-osx-useful-apps.md
Added two new apps to handy apps list. Added instructions for split screen.
N/A
> OSX Updates

- 01-ruby-fundamentals/02-intro-to-object-types.md
I've changed 02-intro-to-object-types.md to include Integer instead of fixnum, include 2.4.0 documentation links and added `nil`.
- Changed 2.3.0 links to 2.4.0 - done
- Changed Fixnum to Integer - done
- Added notes on nil - Done
Another pair of eyes is nice.
> Changed Fixnum to Integer, changed links & added Nil notes.

- 01-ruby-fundamentals/02a-data-structures.md
- 01-ruby-fundamentals/04-comparisons-and-flow-control.md
- 01-ruby-fundamentals/05-compound-and-complex-conditionals.md
- 01-ruby-fundamentals/06-literals.md
- 02-intermediate-ruby/07-enumerable.md
- 08-rails/10-active-record-models.md
Replace Fixnum with Integer
N/A
N/A
> Replace Fixnum with Integer, because Ruby 2.4

- 02-intermediate-ruby/03-class-methods-and-self.md
I wasn't too pleased with either section of this curriculum resource so I refactored it a bunch. I tried to simplify the examples in the initial "review" section as well as provide some more context and verbiage around _why_ we're creating class methods.
None
1. I'd love a fine tooth comb on all changes. 
1. I'd love feedback on whether or not the `Pawn` example at the end is still useful. Primarily, it is doing the `self.new` inside of the class method, but I think it might be oddly confusing/complex. 
1. Looking for feedback on whether or not we should lecture using the `Pawn` example, or use it as an exercise to have folks review with their seat squad?
> class methods vs instance variables

- 00-programming-fundamentals/xx-pseudocode.md
Added full Pseudocode lesson to textbook.
- [  √] Section X still needs some more detailed examples
- [ √] Still need to add "Additional Resources"
Review lesson for any clarifications needed or grammar corrections.
> Pseudocode exercise

- 02-intermediate-ruby/07-enumerable.md
A few updates to the enumerable lecture. Add in a section for the activity on refactoring the loop practice problems.
N/A
Not specifically
> Enumerable lecture

- 00-programming-fundamentals/08-intro-to-automated-tests.md
I'm just fixing a mistake.
- nope
> took out wont_raise

- 00-programming-fundamentals/16-code-coverage-and-simplecov.md
Added spec_helper.rb to simplecov notes.
> added notes on spec_helper.

- 02-intermediate-ruby/lazy-with-let.md
A short resource on testing with `let`.  
None
Any feedback is welcome.
> Added let/before resource.

- 02-intermediate-ruby/02-modules-as-namespaces.md
Change Pokemon cards to Canasta cards, since a Pokemon card doesn't actually have a `MAX_VALUE`.
N/A
Nope
> Improved example code for the Ruby modules lecture

- 08-rails/http-verbs-crud-and-idempotency.md
Big gross blocks of text are great and all, but I felt a table was appropriate here.
N/A
Honestly I'm just going to merge this one immediately.
> Add table of HTTP verbs

- 08-rails/README.md
- 08-rails/how-to-use-postgres.md
A document on how to setup rails with Postgres.  I'm uncertain as to the order this would come in.
Things to do:
Please let me know any feedback.
> Initial document on how to switch to postgres

- 08-rails/rails-forms.md
Just added resources links in a separate section at the bottom.
Just added some resource links at the bottom, making it easier to spot and more consistent with other pieces of the textbook curriculum.  
Probably not needed.
> Just added Resources Section

- 00-programming-fundamentals/01-how-to-osx.md
on line 81 I corrected the right bracket symbol.
This is my first pull request!
Apologies if I'm doing this incorrectly.
> I changed a character

- 08-rails/README.md
- 08-rails/active-record-validations.md
- 08-rails/db-seeds.md
Provide some additional context around examples in lecturing for this week so as not to jump around with context. A few Rails 5 updates.
N/A
Nothing specific - just general reviewing for comprehension
> More Rails Context

- 08-rails/routes-and-resources.md
Just normalizing content to books & authors like other rails textbook sections.
> Normalizing content

- 08-rails/README.md
Just fixed the links in the README for the testing.
Let me know if I made a mistake.
> Revised README for renamed testing docs.

- 09-intermediate-rails/controller-filters-contd.md
- 09-intermediate-rails/controller-filters.md
Remove authorization from the orig controller filters document. Switch examples to reference Book.
Trying to decide if we want to have a separate overview of authorization vs authentication.
> Controller Filters

- 08-rails/installing-foundation.md
Added a section that highlights the settings file that Foundation added to the stylesheets directory so that students can easily customize their site's styles. Mentions sass, with resources - but focuses on the use on variables. 
Review new sections, make sure it's specific enough for students to know how to customize design.
> Added foundation settings section to foundation rails gem lesson

- 09-intermediate-rails/testing-auth.md
Updates notes to cover session testing as well as integration testing for controllers which rely upon the user authorization/authentication. I intentionally did not put all possible examples in here, but hope it covers the basics.
None
I'm not sure how else to explain the `open_session` concept. Open to ideas about visualizations or other descriptive language that could explain this idea.
> Testing Auth/Session

- 10-JavaScript/01-welcome-to-js.md
- 10-JavaScript/01a-ruby-to-js-worksheet.md
- 10-JavaScript/02-fun-with-functions.md
Updated based on my notes and memories from last time. In particular:
Intro to JS lecture
- Remove parts of the intro lecture that rely on functions
- Totally rewrite the piece on loops
- Add a conclusion section
Functions lecture
- Re-order some parts to flow a little better
- Rework the examples to be more concrete
Nothing special, just copy editing and making sure I haven't omitted anything.
> Updates to the first couple JS lectures

- 10-JavaScript/04-js-in-the-browser.md
- 10-JavaScript/05-jquery-intro.md
very basic updates to ID naming convention
None
> jQuery Update

- 10-JavaScript/06-closures.md
> Just added a resource

- 11-Backbonejs/Backbone-Views.md
A small modification to remove a view from the DOM and remove listeners to the view when the delete button is pressed. 
- No
Just a small modification, but I'd appreciate a check.
> Add `.remove()` to Backbone-Views.

- 10-JavaScript/11-testing.md
- Update TBC on Jasmine testing to reflect the new exercise
- Expand discussion of theory and why testing web apps is tricky
- Add boilerplate (additional resources, closing summary)
We had talked about doing it as a group lecture, but I couldn't think of another good example so I just used the model tests in the exercise to demonstrate syntax. This means there's not a clear deliniation b/w lecture and exercise, so I think split into classrooms would be better if possible.
Nope
Nothing particular. @kariabancroft in particular should look over it, since you'll be giving this lecture tomorrow (I think).
> Update JS testing resource

- 12-Capstone/dns.md
Add some examples, clean up some formatting
N/A
Nothing in particular
> Update the DNS lecture

- 01-ruby-fundamentals/02-intro-to-object-types.md
- 01-ruby-fundamentals/06-oo-methods.md
Vocab lists have been added to these resources:
- object types
- methods
I've also put in some substantial work on the objects lecture, but that is a topic for another PR.
Nothing particular
> Add vocab lists to some of the first lectures

- 00-programming-fundamentals/exercises/merge-conflict.md
- 00-programming-fundamentals/exercises/terminal-commands.md
- 01-ruby-fundamentals/exercises/fancify-baby-dragon.md
- 01-ruby-fundamentals/exercises/object-data-types.md
- 01-ruby-fundamentals/exercises/pyramid.md
- 02-intermediate-ruby/exercises/grocery-store.md
- 02-intermediate-ruby/exercises/loop-practice.md
- 02-intermediate-ruby/exercises/object-oriented-design.md
- 08-rails/exercises/erd-practice.md
- 10-JavaScript/exercises/calculator.md
- 10-JavaScript/exercises/exercism.md
- 10-JavaScript/exercises/fortune.md
- 10-JavaScript/exercises/seven-wonders.md
- 11-Backbonejs/exercises/design.md
Move standalone exercises into the appropriate folders within the textbook curriculum. Also added empty folders where there was not a direct relationship.
Goes along with this PR where all of these files were deleted in standalone https://github.com/AdaGold/standalone-exercises/pull/26/files
N/A
Nothing specific I can think of
> Standalone to Textbook

- 02-intermediate-ruby/advanced-variables.md
- 02-intermediate-ruby/source/class_variable_example.rb
- 02-intermediate-ruby/source/class_variable_example_2.rb
- 02-intermediate-ruby/source/constants_example.rb
- 02-intermediate-ruby/source/global_variable_example.rb
- 02-intermediate-ruby/source/instance_variable_example.rb
- 02-intermediate-ruby/source/local_variable_example.rb
- Minor grammar improvements
- Suggested different examples to accompany the lessons: in a common theme using libraries
> suggestions for improving the advanced variables lesson

- 01-ruby-fundamentals/exercises/object-data-types.md
> update question from c7 to c8

- 00-programming-fundamentals/installfest.md
Updating ruby version in the installfest
None
None
> update the ruby version to 2.4.1

- 00-programming-fundamentals/get-to-know-your-text-editor.md
> Update name of package and a typographical error

- 01-ruby-fundamentals/exercises/object-data-types.md
Just gonna merge this right in
> Fix indentation of inline code

- 04-cs-fundamentals/classroom/Array-vs-ArrayList.md
the returned amount for the first array in the first code snippet is 3 not 2.
> first code snippet - correcting returned amount

- 01-ruby-fundamentals/exercises/date-selector-class.md
- 01-ruby-fundamentals/exercises/pyramid-method-practice.md
Rename pyramid exercise, add a new DateSelector exercise. DateSelector is not good for intro OO but is good for additional practice in using built-in Ruby functionality and/or reading the docs.
None
This PR also goes along with [this PR](https://github.com/Ada-Developers-Academy/Teachers-Edition-Textbook/pull/10) from the TET with a potential solution/option for the DateSelector.
> More exercises

- 01-ruby-fundamentals/README.md
- 01-ruby-fundamentals/keword-arguments.md
Almost a complete rewrite of the default parameters lecture, to use keyword arguments instead. This is the modern ruby way of doing things, and matches up with the syntax they'll see in Rails.
Is the code sample too complex? I tried to keep it as simple as I could.
> Discuss keyword arguments instead of default values for params

- 01-ruby-fundamentals/README.md
optional exercises at bottom of chapter readme
> update readme with optional exercises

- 01-ruby-fundamentals/classes.md
caught by classmate during lecture Aug 14.
> Typo in code block

- 02-intermediate-ruby/modules-as-namespaces.md
Standard parens convention
None
None
> cleanup parens to follow our standard conventions

- 01-ruby-fundamentals/intro-to-ruby-gems.md
lolcat is a very small gem to research. Would it be valuable for there to be a second gem to inspect in the one hour groups spend researching gems?
> add table_flipper as an optional gem to research alongside lolcat

- 02-intermediate-ruby/modules-as-namespaces.md
- Added a substantial introduction, which goes over syntax in detail (addressing a complaint we had from students).
- Use a more "computery" example to introduce namespacing, something that might plausibly come up in a real project.
- Remove the final example of nested modules - this isn't something they're likely to see, and it's an extremely confusing bit of code (even to me!).
N/A
- Too heavy of an intro?
- Can you think of a way to demonstrate deeply nested constant lookups realistically without writing a 10000 line library?
- Requested reviews from Jamie because she volunteered, and Chris because he initially authored the library and someone from Carets ought to have a voice on this.
> Updates to the Modules as Namespaces resource

- 02-intermediate-ruby/class-methods-and-self.md
Used to be a hodge-podge of different examples, including the Penguin,
students had identified as frustratingly unrealistic.
Now it's all focused on a Song class that represents a song in a music
player program. This should be a little more concrete, and the common
thread should make it easier to follow.
The exception is the last example, where we demonstrate a factory method.
I honestly just couldn't think of a good example for songs that didn't involve
doing a bunch of weird filesystem stuff (i.e. populate music player from the
contents of a directory).
N/A
Nothing in particular. I've added Jamie because she volunteered, and Chris because it's his week and someone from Carets ought to have a voice on this.
> Rework example code in the class methods lecture

- 02-intermediate-ruby/object-inheritance.md
> fix typo object-inheritance.md 

- 02-intermediate-ruby/exercises/loop-practice.md
One of the common problems we see with TDD is they don't know what to test, so I've added some scaffolding around this. They still have to write the tests themselves, there's just more guidance around what might be interesting.
N/A
Nothing particular
> Loops Worksheet: add scaffolding around testing

- 01-ruby-fundamentals/README.md
- 01-ruby-fundamentals/exercises/while-worksheet.md
Per Dan's note about not having any worksheet practice with while loops. This will go after "complex conditionals" lecture.
None
I put this in a separate file, since the conditionals practice was solely about evaluating many conditional expressions together.
Are these too simple?
> very basic while loop examples worksheet

- 02-intermediate-ruby/enumerable.md
- 02-intermediate-ruby/more-conditionals.md
- 02-intermediate-ruby/more-enumerable.md
Some general cleanup when reviewing the week 4 curriculum.
N/A
> Variety of updates on Week 4 curriculum

- 00-programming-fundamentals/git-diff-pull-and-merge.md
> Fix bullet spacing / numbering on the push/pull activity

- 00-programming-fundamentals/code-coverage-and-simplecov.md
Just because we've reordered WW, and this cites Alouette.
> Just because we've reordered ww

- 02-intermediate-ruby/exercises/hotel-revisited.md
Already got approval from Chris
> Move hotel-revisited to here from standalone-exercises

- 00-programming-fundamentals/exercises/merge-conflict.md
This PR includes several improvements to the merge conflict activity based on instructor feedback from doing this in C7. Specifically:
* Add a Learning Goals section
* Simplify the baseline setup so that recipe files are already created and no file deletion is necessary
* In the reflections section suggest that students write up a set of steps for handling merge conflicts
* Move the collaboration strategies section to the end as it's not necessary information for completing the activity
* Link to the [Git Merge Conflict curriculum](https://github.com/Ada-Developers-Academy/textbook-curriculum/blob/master/00-programming-fundamentals/git-merge-conflicts.md) and [Chris' slides](https://docs.google.com/presentation/d/15OFyyoNJevzk7IpdZCP6VwMLju0MVS2pv0qeETLOa6Q/edit?usp=sharing)
> Updates to merge conflict activity

- 09-intermediate-rails/session.md
Small wording and clarity changes to the flash/session lecture
N/A
Nothing particular. Whoever is doing this lecture for Carets tomorrow should sign off on this.
> Clarifications, especially around flash.now

- 05-html-css/css-framework.md
Modify to specifically reference 6.3.1 version. We may update later, but this is good for now.
None
Nothing specific.
> Update Foundation instructions

- 09-intermediate-rails/automating-foundation.md
A doc on automating Foundation install for Rails.
Feedback welcome
> Finished automating Foundation for Rails.

- 12-Capstone/deploy-aws-eb.md
This adds information about:
* Configuring production database connections
* Setting environment variables
* Creating the Secret Key Base for Rails
> Update AWS Deployment lecture

- 09-intermediate-rails/consuming-apis-in-rails.md
- 09-intermediate-rails/vcr-testing.md
More updates to the Consuming API notes for:
- Ruby naming conventions
- Updates to provide more thorough code examples
- Clear descriptions for when we are doing live code together and when they'll break out to do an exercise
**Note that these updates go along with a new repo https://github.com/AdaGold/SlackAPI**
N/A
Specifically for @tildeee: I want to make sure that with the inclusion of a little hands on activity that we have enough time on the schedule for this resource. Probably 1.5 -2 hours to get through all of it is what we'll need.
> Consuming APIs Notes

- 09-intermediate-rails/consuming-an-api.md
Add guidelines/questions for evaluating an API while exploring
tagging @droberts-ada to make sure this is kind of what he was looking for
> Add guidelines for evaluating an API

- 09-intermediate-rails/consuming-apis-in-rails.md
This is the resource we are looking back on to build api-muncher, so if the 'dotenv' is only in development, the tests fail.
> add 'test' for 'dotenv' - needed for testing.

- 09-intermediate-rails/README.md
- 09-intermediate-rails/ar-serializers.md
Add notes for configuring active model serializers. I ran through the example referencing the "creating apis" notes and adjusting the code established there.
N/A
Nothing specific.
> add serialization resource

- 10-JavaScript/jquery-events.md
Just change an anonymous function to an arrow function.
> updates on jquery events.

- 10-JavaScript/js-objects.md
Particularly around comparing it to Ruby
>  Expand the intro to JS objects a bit

- 10-JavaScript/exercises/functions-worksheet.md
- 10-JavaScript/exercises/objects-worksheet.md
- 10-JavaScript/exercises/ruby-to-js-worksheet.md
- 10-JavaScript/welcome-to-js.md
Updated some of the JS worksheets per updated naming conventions and worksheet adjustments.
Also see the [PR on the TET](https://github.com/Ada-Developers-Academy/Teachers-Edition-Textbook/pull/21).
N/A
1. Are the solutions appropriately formatted?
1. Are these worksheets assigned in the appropriate order?
1. Do we need additional worksheets for ES6-specifics?
> JS Worksheets

- 10-JavaScript/welcome-to-js.md
> Clarification of section that was a little less clear

- doc-template.md
As i'm developing new curriculum I think it would be good to templatize each resource. I just pulled what I think most resources have, but happy for feedback on adding/removing sections.
none
see above
> create resource template

- 10-JavaScript/underscore-templates.md
* Use `forEach` instead of C-style `for` loops
* Follow Airbnb style guide (details in commit message)
> Cleanup code snippets in Underscore templates curriculum

- 11-Backbonejs/collections.md
I rewrote the intro paragraph so that it is more specific to Collections, rather than using the same one from the Models curriculum.
This also includes minor changes to make the code snippets match the Airbnb style guide, and to use non-relative import paths.
> Backbone Collections curriculum cleanup

- 10-JavaScript/underscore-templates.md
- updated the code pen to the generic adadev codepen account
- the lecture didn't include adding the empty div with id todo-list, so i added that
> update codepen, add missing div #todo-list

- 11-Backbonejs/Adding-Custom-Events.md
Just an update to move toward AirBNB styling.
> Updating to keep it in AirBNB styling

- 02-intermediate-ruby/object-composition.md
Small change removing the intro to composition with modules (acts-like) relationships.
-  None
Feedback would be swell.
> Remove Acts-like

- 00-programming-fundamentals/get-to-know-your-text-editor.md
- 00-programming-fundamentals/installfest.md
Just an update to installfest, I took out Sublime mentions as we're not really using it, and updated it to use Ruby 2.5.
- Nope
Let me know if you think we should stay on 2.4.1 or keep the Sublime mentions, or anything else to add.
> Revised Installfest

- 09-intermediate-rails/oauth.md
Adding Logout to the oAuth notes!
None!
> Adding Logout to the oAuth notes!

- 03-leadership-and-inclusion/code-journals.md
> Code Journals

- 00-programming-fundamentals/get-to-know-your-text-editor.md
We did this as a group in pipes for C8 and it made life so much better! Let's standardize the procedure!
> Instructions to add auto-indent keyboard shortcut

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/programming-techniques-pairs-or-solo.md
Just changing wording regarding the Bus factor.
> Change Bus Factor to lottery factor

- 02-intermediate-ruby/lazy-with-let.md
> Fixed a typo

- 00-programming-fundamentals/memoization.md
Hi!
It's so fun to dig through this repo and see how the curriculum evolves. Here's a tiny typo fix because I still daydream about showing up and giving this lecture again someday. :)
Nope!
> Fix a typo I made in 2016.

- 03-leadership-and-inclusion/pair-feedback-and-code-reviews.md
We wanted a way that students could give/receive feedback:
"Another opportunity for the students to get real feedback on their project from someone who is not on the instructional team, have it documented, and have it presented in a meaningful way. Both code feedback and not-code feedback"
I propose the following system:
- giving the students this resource for giving/receiving feedback pro tips
- i wrote a bunch of specifics for feedback (like be specific, etc), but also put a lot of quotes from other resources so it didn't look like i was making up stuff
- requiring the students to spend at least one 15-30 minute session for feedback
- the feedback template for the project (Scrabble) now asks for two things they discussed during their feedback session that they'd be willing to share
Two …
> proposal for pair feedback models

- 08-rails/reference/.rails-template.rb
Reference:
https://trello.com/c/nFYNX6m6/521-add-coverage-and-ds-store-to-rails-template-files
> Update rails template to add to gitignore

- 05-html-css/content-hierarchy.md
> Add main to list of semantic tags

- 02-intermediate-ruby/exercises/hotel-revisited.md
Just updated hotel revisited to note that they need to have Wave 2 completed.
> Update Hotel Revisited

- 08-rails/routes-controllers.md
Like it says on the tin. Also, convert all the double quotes to single quotes, since we don't want Atom putting curly braces after our octothorps.
This section probably still needs some attention - we're introducing route names here, which doesn't make sense because we don't even do view helpers until much later. But, that's a major restructuring that will wait for another cohort.
> Add a summary to the resource on routes and controllers

- 00-programming-fundamentals/git-intro-to-git.md
I was looking at the Intro to Git textbook resource and noticed this weird ￼ thing showing up on the main header. It didn't seem to be serving any purpose so I've removed it.
> Remove non-character bytes in Intro to Git header

- 08-rails/README.md
- 08-rails/forms-strong-params.md
> add strong params resource and update overall readme

- 08-rails/active-record-models.md
I asked these questions in class after this lesson, and it went really well!
None
Nothing special
> Add an activity to the ActiveRecord Models lesson

- 09-intermediate-rails/reference/.rails-template.rb
Another revision, just an update to the rails template to add jquery the lack of which caused errors with some of the foundation code (dropdowns etc).  Also moving to the current gem which works.
Should we simply do the rails template once in our curriculum, we currently update it once for testing and again for Foundation.
> Update to the rails template file

- 08-rails/exercises/request-cycle-practice.md
a HW assignment to practice with the request cycle
N/A
N/A
Should we add more detail? Should I show an annotated version of what I'm thinking of for a simple books request example?
> add request cycle practice exercise

- 08-rails/nested-routes.md
RideShare definitely needs it nested, and in general it's a little more nuanced than we had indicated.
> Address whether to nest create route

- 08-rails/many-to-many-relationships.md
> Deleted 's' from ':book' in line 195

- 08-rails/test-models.md
The idea is to make a "typical" instance of the model in a `before` block, then each test `nil`s something out and verifies it isn't valid.
Nothing special
> Update resource on model testing

- 09-intermediate-rails/reference/.rails-template.rb
Previously it would break when trying to add code to non-existent JS and CSS files. Now it does not do that.
> Update the rails template to work with APIs

- 10-JavaScript/exercises/seven-wonders.md
Just removed all mentions of AJAX, just going to merge this in.
> update seven wonders to reference axios and not AJAX

- 10-JavaScript/exercises/extend-clock.md
A small exercise to extend the clock project and practice using jQuery events to both change classes on a div and using a variable to keep track of state.
> Extending the Clock Project

- React/creating-components-2.md
- React/creating-components.md
- React/lifecycle-methods.md
Removing the links in favor of doing this in a live code as we go along. 
We talked about removing the links to the live code in favor of sharing a live code repo as we go along so it doesn't get out of date. 
N/A
N/A
N/A
> remove the live code links within the lectures

- React/creating-components-2.md
- React/props.md
PROPS need STUDENTS
N/A
N/A
None specifically
> update props to reference students

- React/README.md
- React/styling.md
Filling out the React Styles lecture
- seems pretty complete to me, lmk if you think it's missing something
LMK what you think! What am I missing?
> react styles: inline and external pass through

- React/forms.md
Fixed code style & filenames per Airbnb Style Guide. I also caught one typo on line 260 😃 
~Have you updated the weekly learning goals in the pedagogy resource~
No major changes were made.
> Fix style of JS snippets in react/forms.md

- React/creating-components-2.md
I believe this is a typo in the creating components part 2 lecture.
> Fixing a typo

- 03-leadership-and-inclusion/interview-week-activities.md
suggestions for interview week activities
Please add more should you feel inspired
Is there a better place for me to put this resource? We have a couple of files in this folder that don't feel like they belong now
> suggestions for interview week activities

- React/testing.md
As-is the snapshot management didn't work for me. This fixes it. Source:
https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f
> Make enzyme work with snapshot testing

- 00-programming-fundamentals/debugging-user-reports.md
New resource explaining how to take user reports of erroneous behavior and turn them into repro steps for a developer to use when fixing bugs.
This resource is intended to be used as part of the Rails Debugging activity, since the bugs included in that activity are presented to the student as user reports.
Let me know if there are any more details about how this process works that I should include!
> Resource on debugging based on user reports

- 10-JavaScript/js-ecosystem.md
- React/cra-build-system.md
This is the lecture notes for a lecture on the modern JS build tools ecosystem.
Is this too detailed?
I started explaining the various tools and quickly realized that the students would need some kind of understanding of a build system and the idea of building a software project in the first place, since we basically don't need to do it with Ruby or Rails projects.
But I may have ended up going into too much detail when explaining that background stuff, so let me know if it should be cut down (and what parts you think should be cut if you have any suggestions).
> JS Ecosystem lecture notes

- 02-intermediate-ruby/exercises/hotel-revisited.md
> Connecting changes to Hotel to Hotel-Revisited

- 02-intermediate-ruby/testing-with-guard.md
This adds a resource that explains what Guard is, gives simple installation instructions, and also has a deeper explanation of the Why for using a test watcher like Guard.
There is also a quick overview of the `Guardfile` configuration that we use for Ada projects.
The final two sections (explaining why to use Guard) are largely off-the-cuff or stream of consciousness style, so if anyone has suggested wordsmithing or clean-up I can do for that, please let me know!
> Testing With Guard resource

- 05-html-css/exercises/form_exercise.md
- 05-html-css/solutions/form_exercise/contact.html
This updates the HTML forms exercise's instructions and solution to match the parameter names and values expected by the [back-end implementation](https://github.com/Hamled/paint-shop/tree/complete).
A working version of the back-end is up here: https://ada-paint-shop.herokuapp.com/
You can also try out the solution's contact form at https://ada-paint-shop.herokuapp.com/contact.html.
We should update the README to include the following information:
Once students get their contact form working they can visit https://ada-paint-shop.herokuapp.com/admin/support_tickets to verify that a support ticket was generated from them using the contact form.
In order to access the admin interface you'll need to log in with the following credentials:
• Username: admin
• Password: PaintIsGreat78
> HTML forms exercise code matches back-end

- 02-intermediate-ruby/exercises/more-testing-practice.md
I'm trying to build a few practice exercises involving:
1.  Writing code using loops and arrays, specifically processing a collection of objects
1.  Reading Tests and writing code to match
1.  Writing Tests 
I'll be adding to this today & tomorrow, but this is the first thing to look at. It covers writing tests and reading the tests of another student, and a bit of work with arrays. 
I'd like to see if I we could pair some of our struggling students to do these exercises because I think they might benefit from working together on something small. 
Ideas are **VERY** welcome
> Practice Exercise on Testing

- 09-intermediate-rails/README.md
- 09-intermediate-rails/flash.md
- 09-intermediate-rails/session.md
Split these lectures out so they can be delivered separately.
- [N/A] Have you updated the weekly learning goals in the pedagogy resource
- [N/A] Have you added links to the source (lucidchart, draw.io) for any diagram
N/A
Reviewers chosen and assigned
> split out flash and session lectures

- 09-intermediate-rails/reference/.rails-template.rb
I've updated the `.rails-template.rb` to include Bootstrap.  I have also tested it by building a TaskList app using Bootstrap and dropdown menus etc.
In the [Teacher's Edition](https://github.com/Ada-Developers-Academy/Teachers-Edition-Textbook/pull/48) I have a lesson for a Bootstrap Jigsaw.
Feedback is welcome
> Update rails template to bootstrap

- 09-intermediate-rails/validations.md
Create a resource to describe the difference between client and server side validations. Based on the Trello card, I think the intention of something like this would be a quick HW read rather than an in-class exercise or lecture. As such, please see my two questions below on if it should be added anywhere else. 
- [N/A] Have you added links to the source (lucidchart, draw.io) for any diagram
Does this work for a quick HW reading?
> add validations resource

- 09-intermediate-rails/README.md
- 09-intermediate-rails/code_samples/pet_controller_test.rb
- 09-intermediate-rails/testing-api-controllers.md
Previously we'd just had the tests pre-set in the ada-pets repository.  Do we need a separate lesson or can they get the info from the code?  Regardless I think having a small textbook resource would be helpful.
- [ x ] Have you updated the READMEs with links to new or moved resources?
About to submit an update to ada-pets.
> Add Resource on API Testing

- 08-rails/reference/.rails-template.rb
- 09-intermediate-rails/reference/.rails-template.rb
See title. Generated w/ the program figlet. I did test it!
- [N/A] Have you updated the READMEs with links to new or moved resources?
N/A
Not really
> Add obvious success message to the Rails template

- 10-JavaScript/exercises/js-jquery-review.md
> add review resources: questions for reviewing js and jquery, exercise

- 10-JavaScript/reference/axios/index.js
This instructor-provided code should favor readability-- otherwise teaches them a pattern of copying/pasting for TREK which isn't the goal for this one
> refactors instructor's axios post sample code: hard-code and readable > genericized

- 10-JavaScript/classes.md
For Trello card: Update Classes in JS lecture to be introduced in React Week 1.
https://trello.com/c/IV8UYwA4
TBH: All I really did was review it, make sure it's usable, and change the example class `Book` to `Zine`.
The `Zine` could definitely be reverted back to `Book`, if we feel it's better :P
Lastly, the feedback I request is: Are asking the students to do the exercises for making an Animal class with static methods and inheritance necessary in this curriculum?
The feedback I request is: Are asking the students to do the exercises for making an Animal class with static methods and inheritance necessary in this curriculum?
> updates grammar, changes book example to zine example

- 12-Capstone/README.md
- 12-Capstone/aws-eb.md
- 12-Capstone/deploy-aws-eb.md
I did a couple of things here:
1.  Divided the lecture into a reading which talks about AWS and EB in general and a tutorial which describes nuts and bolts of deploying a sample rails app.
2.  I ran through the tutorial making sure it still works, it does.
3.  Massaged the wording a bit and focused on updating this to focus on independent learning.
Feedback is appreciated
> Update AWS Lecture --> Reading & tutorial

- 01-ruby-fundamentals/exercises/enumerables-jigsaw.md
Students complained about not understanding the spaceship operator on this assignment, so here's some detail!
> add details on spaceship operator to avoid confusion

- 00-programming-fundamentals/exercises/github-verification.md
Just removing atom from an exercise.
> remove mention of atom

- 04-cs-fundamentals/classroom/Arrays.md
- 04-cs-fundamentals/classroom/Introduction to Data Structures.md
- 04-cs-fundamentals/classroom/Introduction to Linked Lists.md
- 04-cs-fundamentals/classroom/Introduction to Recursion.md
- 04-cs-fundamentals/homeworks.md
- 04-cs-fundamentals/internship/Hash Tables.md
- 04-cs-fundamentals/internship/Introduction to Algorithms.md
- 04-cs-fundamentals/internship/Linked Lists.md
- 04-cs-fundamentals/internship/Stacks and Queues.md
- 04-cs-fundamentals/readme.md
List of changes:
- update homework due dates and links for C11
- add links to internship calendar for C10
- the first round of cleanup for organizing CS Fundamentals curriculum: all homework in one place.
To Do: The intent is to create reading notes in each github page and update the readme page to have an organized view of slide decks, reading notes and homework for each topic. This is just the first step towards it.
> C11 updates - CS Fundamentals schedule

- 04-cs-fundamentals/homeworks.md
> Formatting improvements

- 02-intermediate-ruby/README.md
- 02-intermediate-ruby/inheritance-idioms.md
We talk about the syntax of inheritance, but it would be good to introduce some of the vocabulary and design patterns that reflect how inheritance is really used.
This is work that I came up with while thinking deeply about inheritance for [this blog post](https://github.com/droberts-ada/blog-drafts/pull/1). I think it will make OO RideShare go a little smoother, and provide a slick transition into Rails and React some day.
This will be targeted for Tuesday or Wednesday of whatever week contains RideShare (previously 4, now 5).
None
- Shruti, I added you because you reviewed the blog post!
- The example at the end is a lot of code. However, I'm having trouble coming up with good comprehension questions. Any ideas about what to do about all this?
> Add resource on common inheritance idioms

- React/class-components.md
- React/forms-advanced.md
- React/nested-event-handling.md
- React/props.md
- React/react-hello-world.md
- React/state.md
- React/styling.md
- [No] Section X still needs some more detailed examples
- [No] Still need to add "Additional Resources"
> Update React Curriculum

- 01-ruby-fundamentals/exercises/oo-flower.md
- 01-ruby-fundamentals/exercises/oo-library.md
Update Flower and Library OO Exercises.
- [n/a] Have you updated the weekly learning goals in the pedagogy resource?
- [n/a] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [n/a] Have you updated the READMEs with links to new or moved resources?
- [n/a] Section X still needs some more detailed examples
- [n/a] Still need to add "Additional Resources"
> Switch to keyword arguments + fix test error

- 00-programming-fundamentals/installfest.md
Update install fest to simplify git push/pull down the line.
- [n/a] Have you updated the weekly learning goals in the pedagogy resource?
- [n/a ] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [n/a] Have you updated the READMEs with links to new or moved resources?
> Use `current` as the default target for `git push`

- 01-ruby-fundamentals/README.md
- 01-ruby-fundamentals/classes-in-ruby.md
- 01-ruby-fundamentals/classes-part-2.md
The intro to classes was very long, and very mono-directional. I've split it in two, and added a running exercise in addition to the instructor code.
Nope
The only new thing is the exercises. I've run them, but wouldn't hurt to have a double check.
> Split Intro to Classes into 2 lessons, add exercise

- 02-intermediate-ruby/class-methods-and-self.md
> clean up class methods/self lecture

- 00-programming-fundamentals/demo-script.rb
- 00-programming-fundamentals/intro-to-scripts.md
> Add intro to scripting

- 02-intermediate-ruby/api-auth.md
- 09-intermediate-rails/oauth.md
Add a section on API authentication.
I wasn't able to reuse as much as I had hoped - our curriculum around this is scattered across several different sections of the textbook, and was set much later in the course so we had more of a "figure it out" approach.
Follows this approach:
- Introduce the idea of authentication and auth tokens
- Using the browser, see what it looks like when an API requires auth, and how to do so via a query parameter
- Introduce environment variables (much more thoroughly than we have in the past)
- Introduce the dotenv gem and the .env file
- Have them put the two together
None
Nothing special - this one …
> API Authentication

- 05-html-css/imgs/web-server-diagram.svg
- 05-html-css/the-web.md
- 08-rails/installfest-rails.md
- 08-rails/intro-to-testing-controllers.md
- 08-rails/preview-rails.md
- 08-rails/testing-db-in-controllers.md
- Split "controller testing" lecture into two documents:
- intro to testing responses in controllers, for new Unit 2 week 1 (aka week 9)
- testing db changes in controllers, to remain in Media Ranker week
- Pre-rails: have a document of installfest for rails
- Pre-rails: have a preview of Rails (links to installfest and intro to Rails videos), would ideally be pre-Rails week 1 homework
- Rework Intro to Web lecture for Monday morning of HTML/CSS week (refers to previous material in req/res cycle)
> Week 7 (HTML & CSS) and Week 8 (Break Week / preview to Rails) changes

- 00-programming-fundamentals/code-coverage-and-simplecov.md
Small change to add a filter to SimpleCov excluding specs from coverage reports.
- [NA ] Have you updated the weekly learning goals in the pedagogy resource?
- [NA ] Have you updated the weekly assessment in Schoology?
- [NA ] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [NA ] Have you updated the READMEs with links to new or moved resources?
> SimpleCov filtering

- 01-ruby-fundamentals/intro-to-enumerables.md
- 02-intermediate-ruby/enumerable.md
- 02-intermediate-ruby/exception-handling.md
- 02-intermediate-ruby/more-enumerable.md
- 02-intermediate-ruby/object-composition.md
- 09-intermediate-rails/consuming-apis-in-rails.md
- 10-JavaScript/closures.md
- 10-JavaScript/exercises/js-jquery-review.md
- 10-JavaScript/testing.md
- 11-Backbonejs/Backbone-Collections-old.md
- React/apis-get.md
- React/apis-post.md
- React/creating-components.md
- React/events.md
- React/exercises/intro-to-react.md
- React/nested-event-handling.md
This seemed like a good sick day project.
> Replace usage of "seat squad" with "neighbors"

- 00-programming-fundamentals/intro-to-scripts.md
typos, avoid the word "magic," avoid calling something complicated and just say that it's irrelevant at the moment
> reword some phrases

- 04-cs-fundamentals/classroom/CS Fundamentals Introduction.md
This is the write up for the introduction to CS Fundamentals (data structures and algorithms). The lesson starts with the common ground of student account data and goes through the exercise of organizing data in different ways. The intent is to convey that changing the way the information is organized, allows for different methods to be more efficient and other methods to be less efficient.
This will be the first CS Fundamentals lecture note following the homework assignment of Essential Mathematics for software engineers.
While reviewing, give me feedback on:
- what else could be added or changed to drive the lesson home
- spelling and grammar
- any other ideas or suggestions.
> Create Introduction for CS Fundamentals

- 01-ruby-fundamentals/exercises/conditions-worksheet.md
- 05-html-css/content-hierarchy.md
- 09-intermediate-rails/api-tools.md
- 11-Backbonejs/live-code-overview.md
I'm not sure "neighbor(s)" is the correct replacement but "chair pair" is a little awkward with tables that have 3 people.
> Replace "chair pair" with "neighbor(s)"

- 08-rails/rails-forms.md
Updated forms lecture stripping out a lot of model-less forms stuff and focusing on the livecode.  
I also added answers to the exercises as well.
- [NA] Have you updated the weekly learning goals in the pedagogy resource?
- [NA ] Have you updated the weekly assessment in Schoology?
- [NA ] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [NA] Have you updated the READMEs with links to new or moved resources?
> Rails forms update

- 05-html-css/html-forms.md
> Changed <textarea> attribute from "columns" to "cols"

- 08-rails/code_samples/create_controller_test.rb
- 08-rails/code_samples/update_controller_test.rb
- 08-rails/forms-strong-params.md
- 08-rails/testing-db-in-controllers.md
Before, when we did controller testing students knew about fixtures and validations.  Now we need to teach them controller testing without either of those.  So I've updated the lecture (and fixed the missing objectives) to match our new week 1 plans.  
> Update testing in controllers

- 08-rails/README.md
- 08-rails/controllers.md
- 08-rails/intro-to-testing-controllers.md
- 08-rails/requests-and-responses.md
- 08-rails/route-parameters.md
- 08-rails/show-action-intro.md
All the details are here: everything in this PR is probably checked off on this card.
- recontexutalize routing
- The Rails Res/Req Cycle lecture mentions the show action before we do the show action. Smooth that over
- Create resource: Adding Tests to Index
- Create resource: Intro to the Show action and its tests
- Smooth over: Intro to the Show action and its tests -> Livecode
Need to do all of this
- Figure out how to teach testing the show action without a test db
Just realized that testing show, update, and delete would be really hard if they don't have knowledge about the test db/fixtures yet...
> try to bring in controller tests: introduce index action tests, show action tests

- 08-rails/test-setup.md
I'm not 100% sure what this card was calling for.  I _think_ this is what it meant.
> Tell students to replace `~/.rails-template.rb`

- 08-rails/README.md
- 08-rails/exercises/hike-finder/one-to-many.md
- 08-rails/exercises/hike-finder/solutions/one-to-many.md
More exercises!
- [N/A] Have you updated the weekly assessment in Schoology?
Nope, just sections 3 and 4
The last question is kinda tricky. I thought about making it optional, but I think it's good practice.
> Hike Finder Part 2: One-to-Many Relationships

- 00-programming-fundamentals/intro-to-scripts.md
I've been meaning to actually re-write this but it seems good to get
these off my machine.
> Fix a few typos that I noted down during the lecture

- 09-intermediate-rails/session.md
I needed this work done in order to know what my baseline would be for the advanced controller testing lesson.
Changes to the session lesson:
- Add a User model instead of reusing Author
- Call it a UsersController instead of a SessionController to avoid confusion (SessionController almost but doesn't quite match up with the expected vocab around controllers vs models)
- Go into more depth on the examples
- Make it explicit that this is an exercise to be completed by the students, as opposed to a live code
My guess is that as an activity this will take closer to 90 minutes, but that's fine since it just eases into project time, and most of this is directly relevant to what they'll be doing on MediaRanker.
- [N/A] …
> Revamp the session lecture into a full activity

- 08-rails/test-the-test-database.md
> small typo change

- 09-intermediate-rails/view-helpers.md
- Expand the example to be a little more interesting
- Revamp the section on `html_safe` (turns out the old way we presented it exposed an XSS vulnerability - yikes!)
- Add a section on testing
- [N/A] Have you updated the weekly assessment in Schoology?
- [N/A] Have you updated the READMEs with links to new or moved resources?
None
Nothing special.
> Expand the discussion of view helpers

- 09-intermediate-rails/README.md
- 09-intermediate-rails/testing-oauth.md
- 09-intermediate-rails/testing-session.md
The resource itself is pretty short, possibly fits into a half-hour slot. There's lots of other work here around reconciling other resources and removing redundant info.
None
Oof sorry this is coming in so late, hopefully someone has a chance to give it a good look before prime time. I will be taking my prep tomorrow morning, so if you see a change that needs to be made, make it!
I will switch the calendar so that view helpers comes before this lesson, since that gives us a little more time to get eyes on this.
> Add Resource on Session Testing

- 04-cs-fundamentals/classroom/Whiteboarding-Tips.md
Just an updated slideshow link and remove HTML from the page replacing it with markdown.
> updated slidedeck & creative commons link

- 09-intermediate-rails/reference/.rails-template.rb
I added a  \n to application.js jquery sprocket injection. This was preventing jquery from loading when an app was deployed to Heroku, creating issues when specifying request methods like post and delete in link_to. 
> Fixed bug in rails-template.rb

- 00-programming-fundamentals/exercises/git-pull-requests.md
Make an intro exercise for PRs. The students have been definitely exposed to them and should already have a good grasp on them, honestly
N/A
Is this good enough for tomorrow?
> draft for PR small group exercise

- 09-intermediate-rails/oauth-contd.md
Need a resource that actually goes into the detail on Friday
> begins building the oauth detail lecture

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/continuous-integration.md
Short description of what CI is and why it matters, followed by an activity to set up TravisCI for a project. The activity is intended as an exercise in reading documentation - I gave them a `.travis.yml` that I know is good, along with a link to the docs, and that's it. Estimated time 1 hour.
None
Do they need more structure for the activity?
> Add resource on TravisCI

- 10-JavaScript/arrow-functions-anonymous-this.md
- 10-JavaScript/arrow-functions.md
> Re-order sections in arrow functions lectures, split into two documents

- 10-JavaScript/reference/trek/trek-design-scaffolding.md
See code (it includes a "purpose" section)
- [N/A ] Have you updated the weekly learning goals in the pedagogy resource?
- [N/A] Have you updated the weekly assessment in Schoology?
- [N/A] Have you updated the READMEs with links to new or moved resources?
None
- Does this feel like enough help? Too much?
- How will we remember that we have this for next cohort?
> Add design scaffolding for TREK

- React/forms.md
The `<form>` is already a single element so the `<div>` is extraneous.
> Remove unnecessary `<div>`

- 02-intermediate-ruby/api-auth.md
Clarify how to get an api key from MovieDB
- [ N/A] Have you updated the weekly learning goals in the pedagogy resource?
- [ N/A] Have you updated the weekly assessment in Schoology?
- [ N/A] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [ N/A] Have you updated the READMEs with links to new or moved resources?
NONE
> improve moviedb setup instructions

- 00-programming-fundamentals/get-to-know-your-text-editor.md
- 00-programming-fundamentals/installfest.md
C11 taught us a couple of things about using VS Code, and we want these changes:
1. Remove Rufo
1. Add this extension: https://marketplace.visualstudio.com/items?itemName=adadevelopersacademy.reindent-on-save "Reindent on Save"
1. Add detail: Confirm that VSCode lives in Applications (not Downloads)
1. Change in installfest in git config: `$ git config --global core.editor "code --wait"`
1. Change "decent" -> "good"
> Update Installfest and VS Code with workflow improvements

- 01-ruby-fundamentals/README.md
- 01-ruby-fundamentals/compound-and-complex-conditionals.md
- 01-ruby-fundamentals/conditional-control-structures.md
Split lesson into 
1. truth tables / parse trees (compound-and-complex-conditionals.md)
2. conditional control structures (conditional-control-structures.md)
and
added condiionals-worksheet.md to be an exercise at the end of compound-and-complex-conditionals.md
- [N/A ] Have you updated the weekly learning goals in the pedagogy resource?
- [ N/A] Have you updated the weekly assessment in Schoology?
- [ N/A] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [ will do that next] Have you updated the READMEs with links to new or moved resources?
- [ no] Section X still needs some more detailed examples
- [ no] Still need to add "Additional Resources"
Please utilize the built-in GitHub Reviewers functionality to assign …
> split and modified conditional lessons

- 00-programming-fundamentals/installfest.md
We fixed the problem with the debugger, and now there are nice instructions.
> Install with rbenv

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/study-like-a-programmer.md
By request, have some air time about study techniques, which I have "cleverly" named "study like a programmer" for some reason (i'm very attached to this name for some reason but I'm open to feedback)
> creates study like a programmer resource

- 00-programming-fundamentals/how-to-macOS.md
Not having to memorize the screenshot keyboard shortcuts is nice.  Mojave has an app for that now.
> Add section about Screenshot.app

- 03-leadership-and-inclusion/classroom-contract-pre-work.md
a document for targeted questions for classroom contract activity
Note the PR also for TET
> adds student-facing doc for classroom contract pre-work

- 01-ruby-fundamentals/conditional-control-structures.md
I've seen name length be used to single out people of color so I thought it might be good to use an example that wasn't explicitly singling out people with long names.
> Change name length conditional to places visited conditional

- Review/week-1/conditionals_methods_review.md
This is a review directory for daily review lessons
- [ NA] Have you updated the weekly learning goals in the pedagogy resource?
- [ N/A] Have you updated the weekly assessment in Schoology?
- [ NA] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [NA ] Have you updated the READMEs with links to new or moved resources?
> Review directory

- 01-ruby-fundamentals/scope.md
This exercise has usually worked well in the past, but the code we give them (intentionally) halts code... which is a weird hiccup. This change comments the lines out, and then gives instructions on when to uncomment/comment
> comments to lines of code that (intentionally) halt

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/about-problem-solving-exercises.md
- 01-ruby-fundamentals/scope.md
document for intro to problem-solving exercises
Has a lot of info that instructors should cover that C11 feedback said would be helpful
> document for intro to problem-solving exercises

- Review/week-1/scope_review.md
Adding a review resource for scope to be used at the start of the day the day after the scope lesson is given
- [ NA] Have you updated the weekly learning goals in the pedagogy resource?
- [ NA] Have you updated the weekly assessment in Schoology?
- [ NA] Have you added links to the source (lucidchart, draw.io) for any diagram?
- [NA ] Have you updated the READMEs with links to new or moved resources?
- [NA ] Section X still needs some more detailed examples
- [ NA] Still need to add "Additional Resources"
> warm-up review activity for scope

- 00-programming-fundamentals/git-intro-to-git.md
I've already had a student say they wish they'd saved working versions of their calculator project so I feel like this is very relevant to add.
> Add a 2nd reason to the 'why git?' section

- 01-ruby-fundamentals/intro-to-ruby-gems.md
Replaced with "A Gem will contain some files with ruby code, just like the ones you've been creating." as a gem doesn't always have a new class. For instance 'colorize' extends the String class.
> removed "gem contains one or more Ruby Classes"

- Review/week-2/debug_review.md
Debug warmup to do as a morning activity
> Add debug warmup

- 00-programming-fundamentals/git-diff-pull-and-merge.md
This lecture needed a bunch of little TLC, so it's more altered than just having added the new Push content
Please read through this top to bottom, I'm trying to make sure that all of the examples are consistent. Currently they are using the \```bash syntax, no $.
> Updating the .gitignore lecture to include le puush

- 00-programming-fundamentals/git-intro-to-git.md
We don't have anything at the end of the lesson listing all the commands and it seemed helpful.
> Add summary table to intro-to-git

- 01-ruby-fundamentals/exercism.md
We have been wanting to replace our [Weekend Warrior Ruby exercises](https://github.com/AdaGold/weekend-warrior) with Exercism, because they are essentially the same thing, but Exercism is more maintained
SOOOOOOOOOOOOOOOO this is great honestly, and will save us so much work! However, EVERY EXERCISM RUBY EXERCISE REQUIRES USING CLASSES! **So this must go in at week 3 or later if we do this**
> adds doc on using exercism in Ruby

- 01-ruby-fundamentals/exercises/oo-worksheet.md
A worksheet that starts off very step-by-step. Can be taught right after classes, state, and behavior. Does not require self or attr methods
> classes worksheet

- 04-cs-fundamentals/internship/code-reviews.md
Fixed bad spelling Thanks Hana
> Fix spelling

- 04-cs-fundamentals/classroom/Binary.md
> Just adding Video Lesson link

- Review/week-3/classes-day02.md
A somewhat open ended guided practice example to review the concepts learned on day 1 of classes.
> guided practice to review day 1 of classes

- 02-intermediate-ruby/class-methods-and-self.md
Reorganized lesson to focus on the Song example to learn class methods and class variables. The Library example was moved to the end as a cautionary tale.
> reorg of class methods and variables lesson to focus on song example

- Review/week-3/class-methods-review.md
Review questions class methods to discuss with neighbors.
> class method review questions doc

- 00-programming-fundamentals/commands-queries.md
Please double check for any references still remaining for Slack project/api's
> Removing slack from cmd&query

- 04-cs-fundamentals/internship/exercises/binary-tree.md
- 04-cs-fundamentals/internship/exercises/stacks-queues-conceptual-questions.md
> Csfun tree exercises

- 02-intermediate-ruby/references-and-values.md
I noticed that all the students in Branches did NOT expect changes within the `short_strings` method to affect the input so I wanted to rewrite that example to have the "shock value" it was written to have.
> Update references and values lesson to present changing underlying object as a problem rather than a solution

- intro-to-web/api-jigsaw.md
> creates a jigsaw activity for apis in a new intro-to-web dir

- 04-cs-fundamentals/internship/binary-search-trees.md
> Updated a typo for a post-order traversal

- 08-rails/ERB-and-Layouts.md
- 08-rails/active-record-migrations.md
- 08-rails/active-record-models.md
- 08-rails/intro-to-testing-controllers.md
- 08-rails/reference/.rails-template.rb
- 08-rails/requests-and-responses.md
- 08-rails/route-parameters.md
- 08-rails/show-action-intro.md
- 08-rails/using-active-record-in-code.md
- 09-intermediate-rails/reference/.rails-template.rb
I'm smoothing out Rails week 1! I'm making 5 PR's, one for each day, so that it isn't super overwhelming to review! These changes are meant to smooth transitions between lessons by improving consistency and making sure all errors are addressed!
I messed up so monday and tuesday are in this one WHOOPS
> Rails Smoothing Week 1 Day 1&2

- 08-rails/common-view-helpers.md
- 08-rails/rails-forms.md
- 08-rails/safety-idempotency.md
- 08-rails/testing-db-in-controllers.md
More Rails Smoothing, condensed for your enjoyment.
> Rails Week 1 Day 3 Smoothing

- 01-ruby-fundamentals/README.md
> update the link for Worksheet: Object Types

- 00-programming-fundamentals/README.md
> provide the correct link for Submitting Projects

- 08-rails/exercises/hike-finder/one-to-many.md
> update "likes" to "hikes"

- 09-intermediate-rails/flash.md
short exercise to add `flash` to TaskList or RideShareRails
> adding an exercise to flash lesson

- 09-intermediate-rails/testing-controllers-revisited-activity.md
https://trello.com/c/X2641XIe
If this PR gets approved and merged in, then whoever presses the merge button should go and delete this file from TET: https://github.com/Ada-Developers-Academy/Teachers-Edition-Textbook/blob/master/09-intermediate-rails/controller_testing_review.md
> Make controller test review student-facing and self-directed

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/intro-to-wireframes.md
The most bare doc for intro to wireframes
> creates an initial doc for intro to wireframes for c12

- 10-JavaScript/testing.md
> JS Testing

- 10-JavaScript/arrow-functions.md
- 10-JavaScript/exercises/functions-worksheet.md
- 10-JavaScript/first-class-functions.md
- 10-JavaScript/functional-expressions.md
- 10-JavaScript/functions-intro.md
* Also fix a few small issues in the arrow functions lesson.
See https://trello.com/c/qqkZpUUF/1511-week-15-update-intro-to-functions-to-handle-es6-function-naming
> Update function naming to avoid repetition

- 10-JavaScript/README.md
- 10-JavaScript/async-intro.md
Need an intro to async, to be delivered immediately before GET requests/AJAX
**Looking for accuracy of language**. I think that the flow/delivery can be adjusted after the lesson is given.
> outline for async intro lesson

- 10-JavaScript/README.md
- 10-JavaScript/axios-post.md
Creates a new post req resource that doesn't rely on jQuery
> creates axios post resource without jQuery

- 10-JavaScript/dom-manipulation-live-code-notes.md
- 10-JavaScript/js-in-the-browser.md
JS in the browser was originally a lead-up to a sub-unit of jQuery
Now that we've removed jQuery from the curriculum, the material should change to reflect: introductory material, and material that is good pre-knowledge for React
> reworks js in the browser day

- 10-JavaScript/exercises/summary-worksheet.md
> creates summary worksheet

- 00-programming-fundamentals/installfest.md
> correct the browser name

- 00-programming-fundamentals/README.md
- 00-programming-fundamentals/intro-to-your-dev-environment.md
Instead of several links on the calendar, create one document that summarizes the three links that need to get through.
> creates intro to dev env summary

- 02-intermediate-ruby/csv-as-a-database.md
Big things to note:
1. REMOVES PRETTY MUCH ALL OF THE WEIRD FORMS OF SYNTAX and focuses on giving ONE recommendation: using `read`, headers, and an each loop
1. More focus on concept, then syntax
1. Makes CSV write material optional. Only do this if there's time and interest.
> removes CSV write as mandatory, adds structure to building CSV.read in a meaningful way

- 02-intermediate-ruby/README.md
- 02-intermediate-ruby/testing-with-before-and-let.md
> renames file to add before, adds conclusion, detail about instance vars

- 02-intermediate-ruby/class-methods-and-self.md
I wrote a jukebox example so we have a positive example for design that doesn't use class variables
> added jukebox example to replace library cautionary tale

- 05-html-css/README.md
- 05-html-css/preview-html-css.md
Instead of shoving things into the calendar, since it's a pretty long list of links, I wanted to put it into a document.
I started to work off of a Google Doc, but it felt really confusing about how to organize the due dates in a way that felt readable.
Now, I imagine the calendar event homework text to look more like:
Complete Part 1 of HTML/CSS Pre-Work Assignment, due Monday (link)
Complete Part 2 of HTML/CSS Pre-Work Assignment, due Tuesday (link)
> adds file for html/css pre-work

- 04-cs-fundamentals/classroom/reviews/sorting.md
A set of warmup questions for the CSFun online lesson, C13.
> sorting walk-in questions

- 04-cs-fundamentals/internship/exercises/hash-tables-review.md
Warmup for virtual CSFun for C12 tomorrow.
> hash tables warmup

- 04-cs-fundamentals/internship/hash-tables.md
> Minor grammar fixes

- 10-JavaScript/closures-continued.md
This just removes the jQuery from the continued closures lesson and replaces it with vanilla JS (pretty simple change now).  I also moved codepen to codesandbox just to give a more familiar environment to students (it's like VS code).  It also lets me fork my own pens, which codepen has stopped doing.  
If codesandbox is acceptable I'll switch the sandboxes to a generic `instructors@ada` account and update the links.  
- Should this be a supplementary resource or standard part of the curriculum?
- Should I do a video lesson on this?
> More Closures resource

- 04-cs-fundamentals/classroom/reviews/hashes-review.md
> hash tables review

- 04-cs-fundamentals/classroom/reviews/functions-recursion-review.md
> functions review

- roundtables/week09/day05-javascript-adagrams-and-functions.md
Let me know if any of the questions need to be adjusted. Some of this material has been reviewed, but having had hands-on time might have made new questions emerge.
> added js adagrams and functions review materials

- roundtables/week10/day03-adapets.md
> first pass at questions

- roundtables/week11/day-2-components-timeline.md
> draft for identifying components and timeline guide

- React/exercises/identifying-components.md
Update for C13: there isn't enough time to move this off of mediaranker, but I thought there could be more detail
> adds more details to the existing prompts

- roundtables/week11/day-5-exercism-tic-tac-toe.md
Still needs more detail from Tic Tac Toe project before I can write a detailed question on it.
> starts guide for exercism for week 11

- React/useEffect.md
> fix image link

- React/forms.md
should be app not student collection
> Correct wrong filename

- 08-rails/rails-forms.md
I added the edit and update solution to a details tag so students have this for reference. I couldn't get the formatting quite right. If anyone's able to fix that formatting and merge it in, that'd be awesome
> edit and update solution

- 08-rails/using-active-record-in-code.md
Included updated code for show test so that the test doesn't fail now that the controller/views point to the database.
> updated show test

- 08-rails/testing-db-in-controllers.md
moved update test solution to details tag, and saved talking about invalid parameter tests for next week when we complete validations.
> moved solution to details tag

- 08-rails/README.md
Renumbered Week 2 in the read me to match the branches in ada-books repo
> # week 2 to match branches in AdaGold/ada-books

- 08-rails/model-logic.md
Just adding notes for Ada books to add the changes into the example project
> add update code to ada-books

- 09-intermediate-rails/flash.md
https://github.com/AdaGold/ada-books/tree/30-flash
> updates code snippets to match ada-books

- 09-intermediate-rails/controller-filters-contd.md
The lesson material didn't have the code that is currently in the ada-books implementation; here's a quick attempt at trying to make them the same and have explanation around it. @jmaddox19 not sure what the content of the video is, so please check to see that this aligns with your video and change it if not!
> require_login filter except current_user action, not only on create

- 09-intermediate-rails/creating-apis.md
- 09-intermediate-rails/rails-api-intro.md
Big things:
- Since this is "after" the ada-pets-node project, I've conformed the field names to the ones that are on that project, for the sake of consistency
- Following that, I made the seed data also the same exact seed data from that project, with the exception of adding Jared's Piper.
- Note that I just made up one pets fixture, which is Sarah's dog.
- I did some tiny grammar cleanups
- I changed how the test for checking all the API keys worked -- feel free to change this!
- I changed "yasssss" to "yessssss" bc there's valid criticism for "yaaaaaaaaaas" to be appropriative of black gay culture
- I changed some wording of things so it'd be less "hard-coded"
This is where the new Pets API Repo is: https://github.com/AdaGold/ada-pets-rails-api
> conforms attrs to ada-pets-node attrs, grammar cleanup, link cleanup

- 09-intermediate-rails/creating-apis.md
I forgot to add the show action, and didn't do so until the end... the show action and tests are here https://github.com/AdaGold/ada-pets-rails-api/tree/show-action-and-tests
I decided to word this text more generically in case this changes in the future.
> rewords show action solution branch more generically

- 04-cs-fundamentals/interview-prep/interview-practice-exercises.md
> added additional interview problems

- 00-programming-fundamentals/installfest.md
> Update installfest on Rectangle 

- 00-programming-fundamentals/git-intro-to-git.md
Added notes on the master branch and how things will and should change.
> add notes on the master-branch and how it will change

- 10-JavaScript/js-ecosystem-review.md
> added review
